// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApg4PMxwDHAPt9qVxg6V2V8z2XHadJb5M',
    appId: '1:292093703003:web:fa66f15a004ea176a9207e',
    messagingSenderId: '292093703003',
    projectId: 'flutter-chat-app-f9f65',
    authDomain: 'flutter-chat-app-f9f65.firebaseapp.com',
    storageBucket: 'flutter-chat-app-f9f65.appspot.com',
    measurementId: 'G-VCR2TPGC0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE7EYeWLgz09HwxkoNjhRfXxCu8Qasfxc',
    appId: '1:292093703003:android:106670d6a525551fa9207e',
    messagingSenderId: '292093703003',
    projectId: 'flutter-chat-app-f9f65',
    storageBucket: 'flutter-chat-app-f9f65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMwR0R-LbUI7MwVnIeyc5mHMqwOX-Ztx8',
    appId: '1:292093703003:ios:f29d38ee9c34d287a9207e',
    messagingSenderId: '292093703003',
    projectId: 'flutter-chat-app-f9f65',
    storageBucket: 'flutter-chat-app-f9f65.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMwR0R-LbUI7MwVnIeyc5mHMqwOX-Ztx8',
    appId: '1:292093703003:ios:55f5d51a9ddaa5cea9207e',
    messagingSenderId: '292093703003',
    projectId: 'flutter-chat-app-f9f65',
    storageBucket: 'flutter-chat-app-f9f65.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
